services:
  - type: web
    name: philosophy-api
    plan: free
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    healthCheckPath: /swagger/v1/swagger.json
    autoDeploy: false
    envVars:
      - key: PORT
        value: "8080"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"
      - key: Database__Provider
        value: Postgres
      - key: ConnectionStrings__Default
        value: Host=ep-purple-glade-ar3zuno6-pooler.c-4.us-west-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_tzo0hFPMsAv2;SSL Mode=Require
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: AIPhilosophy365
      - key: Jwt__Audience
        value: AIPhilosophy365Clients
      - key: Seed__AdminEmail
        value: admin@philosophy365.app
      - key: Seed__AdminPassword
        value: Admin@12345!
      - key: Mock__FfmpegPath
        value: ffmpeg

  - type: web
    name: philosophy-web
    plan: free
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile.web
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: PORT
        value: "8080"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"
      - key: Api__BaseUrl
        value: https://philosophy-api.onrender.com

  - type: web
    name: philosophy-worker
    plan: free
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile.worker
    healthCheckPath: /healthz
    autoDeploy: false
    envVars:
      - key: PORT
        value: "8080"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__Provider
        value: Postgres
      - key: ConnectionStrings__Default
        value: Host=ep-purple-glade-ar3zuno6-pooler.c-4.us-west-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_tzo0hFPMsAv2;SSL Mode=Require
      - key: Mock__FfmpegPath
        value: ffmpeg
      - key: Mock__PublicBaseUrl
        value: https://philosophy-api.onrender.com